import type { Metadata } from "next";
import { Poppins, Tajawal } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme-provider";
import "./globals.css";

const tajawalSans = Tajawal({
  variable: "--font-tajawal-sans",
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
});

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="auto" suppressHydrationWarning>
      <body
        className={`${tajawalSans.variable} ${poppinsSans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
